### ISSUE TITLE
Layout fixes

### ISSUE THREAD

**Issue by jaredjburgess** [Stepsize/atom-better-git-blame#2]
Since there is no open PR, here are my comments for the final view visuals (based on master this morning 22/09/17).

Only a few minor comments, most of the corrections have already been taken care of.

<img width="1680" alt="screen shot 2017-09-22 at 11 40 32" src="https://user-images.githubusercontent.com/13640069/30741307-2e02bf0a-9f8c-11e7-91a3-f615c753d254.png">

1. The issue icon (the one we use for the specific state of the linked issue, that sits under the title), is not aligned vertically to the content (in this case `#40 by nomeyer`)
<img width="461" alt="screen shot 2017-09-22 at 11 52 38" src="https://user-images.githubusercontent.com/13640069/30741435-aae2da82-9f8c-11e7-88b2-0b2a705485aa.png">

2. The commit icon vertical alignment which you are already aware of

3. (Minor) the thin font weight is still being picked up for the headers of the tooltip (when using the atom material theme), is there a way to fix this without having knock on effects to the other themes?

@nomeyer on another note are we planning to update the names displayed to abbreviated versions (e.g. N. Omeyer)? Or is this being held off? I don't see a reason why given the implementation itself would be trivial given that we have the full name strings already.

**Comment by pthm** [comment]
@jaredjburgess @nomeyer Are these issues resolved with the 0.1.1 release? If so I'll close this

**Comment by nomeyer** [comment]
I think the commit icon alignment issue is still there. Dunno about the material theme issue. So we could keep this open for now (although I'm aware of the difficulty fixing it, we can deal with it for now).

**Comment by nomeyer** [comment]
Split into individual issues (#7, #9, and #10). Closing this.
